import express from 'express';
import { createServer } from 'http';
import { Server } from 'socket.io';
import cors from 'cors';
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';
import dotenv from 'dotenv';
import mongoose from 'mongoose';

import { connectDB } from './config/db.js';
import redisClient from './config/redis.js';
import { initKafka, producer } from './config/kafka.js';
import { authMiddleware } from './middleware/auth.js';
import User from './models/User.js';
import Quiz from './models/Quiz.js';
import Submission from './models/Submission.js'; 

dotenv.config();
connectDB();
initKafka();

const app = express();
app.use(cors());
app.use(express.json());

const httpServer = createServer(app);
const io = new Server(httpServer, { cors: { origin: '*' } });

// Auth Endpoints
app.post('/api/auth/register', async (req, res) => {
  try {
    const { tenantId, name, email, password, role } = req.body;
    const hashedPassword = await bcrypt.hash(password, 10);
    const user = await User.create({ tenantId, name, email, password: hashedPassword, role });
    const token = jwt.sign({ id: user._id, tenantId, role }, process.env.JWT_SECRET);
    res.status(201).json({ token, user: { name, email, role, tenantId, id: user._id } });
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});

app.post('/api/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await User.findOne({ email });
    if (!user || !(await bcrypt.compare(password, user.password))) {
      return res.status(401).json({ message: 'Invalid credentials' });
    }
    const token = jwt.sign({ id: user._id, tenantId: user.tenantId, role: user.role }, process.env.JWT_SECRET);
    res.json({ token, user: { name: user.name, email: user.email, role: user.role, tenantId: user.tenantId, id: user._id } });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// Quiz Endpoints
app.post('/api/quizzes', authMiddleware, async (req, res) => {
  try {
    if (req.user.role !== 'teacher') return res.status(403).json({ message: 'Forbidden' });
    const code = Math.random().toString(36).substring(2, 8).toUpperCase();
    const quiz = await Quiz.create({ ...req.body, code, teacherId: req.user.id, tenantId: req.user.tenantId });
    res.status(201).json(quiz);
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});

app.get('/api/quizzes/teacher', authMiddleware, async (req, res) => {
  const quizzes = await Quiz.find({ teacherId: req.user.id, tenantId: req.user.tenantId });
  res.json(quizzes);
});

app.get('/api/quizzes/join/:code', authMiddleware, async (req, res) => {
  const quiz = await Quiz.findOne({ code: req.params.code, tenantId: req.user.tenantId });
  if (!quiz) return res.status(404).json({ message: 'Quiz not found' });
  res.json(quiz);
});

// PURE LIVE TELEMETRY ENGINE VIA REDIS
const broadcastLeaderboard = async (quizId) => {
  try {
    console.log(`Compiling clean Redis cache live telemetry matrices for quiz: ${quizId}`);
    
    // 1. Fetch raw scored set data maps back out of your container memory
    const rawLeaderboard = await redisClient.zRangeWithScores(`quiz:${quizId}`, 0, -1, { REV: true });
    
    if (!rawLeaderboard || rawLeaderboard.length === 0) {
      console.log(`⚠️ Redis cache data is currently empty for room: quiz:${quizId}`);
      // Send down clean empty arrays to clear the UI from the hanging loading state
      io.to(quizId).emit('leaderboard_updated', []);
      return;
    }

    // 2. Map and filter items dynamically using user schema parameters
    const mappedLeaderboard = await Promise.all(rawLeaderboard.map(async (item, index) => {
      try {
        // Force clean string formatting to strip out any weird Redis stringification artifacts
        const cleanUserId = String(item.value).trim().replace(/^["']|["']$/g, '');
        
        // Validate that it is a valid 24-character hex string before querying Mongo
        if (!mongoose.Types.ObjectId.isValid(cleanUserId)) {
          console.log(`⚠️ Invalid Object ID skipped in leaderboard parsing: ${cleanUserId}`);
          return null;
        }

        const user = await User.findById(cleanUserId);
        
        // Strict Gate check: Exclude any admin/teacher accounts from showing in results list
        if (!user || user.role !== 'student') return null;

        // Calculate relative podium ranking labels and award metadata medals
        let medal = "";
        if (index === 0) medal = "🥇";
        else if (index === 1) medal = "🥈";
        else if (index === 2) medal = "🥉";

        return {
          id: cleanUserId,
          name: user.name,
          score: item.score,
          position: `${index + 1}`,
          medal: medal
        };
      } catch (err) {
        console.error("Error processing individual leaderboard item:", err);
        return null;
      }
    }));

    // Drop empty indices generated by hidden teacher profile rows or broken IDs
    const cleanedLeaderboard = mappedLeaderboard.filter(player => player !== null);

    console.log(`Successfully broadcasted ${cleanedLeaderboard.length} structured records from Redis cache memory.`);
    io.to(quizId).emit('leaderboard_updated', cleanedLeaderboard);

  } catch (err) {
    console.error('Redis transmission compilation failure:', err);
  }
};

// Socket.IO Orchestration Flow Framework
io.on('connection', (socket) => {
  console.log(`Socket Connected: ${socket.id}`);

  socket.on('join_room', ({ quizId }) => {
    socket.join(quizId);
  });

  socket.on('start_quiz', async ({ quizId, tenantId }) => {
    try {
      const quiz = await Quiz.findOneAndUpdate({ _id: quizId, tenantId }, { status: 'active', currentQuestionIndex: 0 }, { new: true });
      io.to(quizId).emit('quiz_started', { question: quiz.questions[0], index: 0 });
    } catch (err) {
      console.error("Start Quiz error:", err);
    }
  });

  socket.on('next_question', async ({ quizId, tenantId }) => {
    try {
      const quiz = await Quiz.findOne({ _id: quizId, tenantId });
      
      if (!quiz) {
        console.error(`Next Question Error: Quiz not found for ID ${quizId}`);
        return;
      }

      const nextIndex = quiz.currentQuestionIndex + 1;

      if (nextIndex < quiz.questions.length) {
        quiz.currentQuestionIndex = nextIndex;
        await quiz.save();

        console.log(`Advancing Quiz ${quizId} to Question Index ${nextIndex}`);
        io.to(quizId).emit('next_question', { 
          question: quiz.questions[nextIndex], 
          index: nextIndex 
        });
      } else {
        quiz.status = 'ended';
        await quiz.save();
        
        console.log(`Quiz ${quizId} has reached the end.`);
        io.to(quizId).emit('quiz_ended');
      }
    } catch (err) {
      console.error('Socket next_question failure:', err);
    }
  });

  socket.on('submit_answer', async (data) => {
    try {
      // 1. Stream the payload directly to Kafka broker topic log
      await producer.send({
        topic: 'quiz-submissions',
        messages: [{ value: JSON.stringify(data) }]
      }).catch(e => console.log("Kafka broker offline notification (Bypassing direct hook):", e.message));

      // 2. IMMEDIATE WRITE LOGIC: Process evaluations locally instantly
      const { tenantId, quizId, studentId, questionId, selectedAnswer } = data;
      
      const quiz = await Quiz.findOne({ _id: quizId, tenantId });
      if (quiz) {
        const question = quiz.questions.id(questionId);
        if (question) {
          const isCorrect = question.correctAnswer === selectedAnswer;
          const points = isCorrect ? 10 : 0;

          let submission = await Submission.findOne({ quizId, studentId, tenantId });
          if (!submission) {
            submission = new Submission({ tenantId, quizId, studentId, answers: [], score: 0 });
          }

          const alreadyAnswered = submission.answers.some(a => a.questionId.toString() === questionId.toString());
          if (!alreadyAnswered) {
            submission.answers.push({ questionId, selectedAnswer, isCorrect });
            if (isCorrect) submission.score += points;
            await submission.save();
            
            // HYBRID SYNC: Force clean string mapping into the Redis container memory set
            const cleanStudentIdStr = String(studentId).trim().replace(/^["']|["']$/g, '');
            console.log(`Writing to Redis -> Key: quiz:${quizId}, Student: ${cleanStudentIdStr}, Points: ${points}`);
            
            await redisClient.zIncrBy(`quiz:${quizId}`, points, cleanStudentIdStr);
          }
        }
      }

      // 3. Fire computed data down the WebSocket line room pipe
      await broadcastLeaderboard(data.quizId);

    } catch (error) {
      console.error("Direct real-time answer ingestion crash:", error);
    }
  });

  // TARGETED LEADERBOARD ROOM DEMAND INTERCEPT HOOK
  socket.on('get_leaderboard', async ({ quizId }) => {
    await broadcastLeaderboard(quizId);
  });
});

const PORT = process.env.PORT || 5000;
httpServer.listen(PORT, () => console.log(`Server running on port ${PORT}`));